//Gautham Sathish
//File I/O Assignment
//Made to simulate a login screen with proper registration, forgotten password feature and normal login
package sathishgauthamsecurelogin;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.ArrayList;//array list library
import java.util.logging.Level;
import java.util.logging.Logger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import static jdk.nashorn.internal.objects.NativeString.substring;
import java.util.Scanner;

public class SathishGauthamSecureLogin extends javax.swing.JFrame {

    public SathishGauthamSecureLogin() {
        initComponents();
        read();
    }

    String newUsername = "";//string to store a registering user's username
    String newPassword = "";//string to store a registering user's password
    String newEmailAddress = "";//string to store a registering user's email address
    String newFirstName = "";//string to store a registering user's first name
    String newLastName = "";//string to store a registering user's last name

    String oldUsername = "";//string to store a registered user's username
    String oldPassword = "";//string to store a registered user's password
    String oldEmailAddress = "";//string to store a registered user's email address
    String oldFirstName = "";//string to store a registered user's first name
    String oldLastName = "";//string to store a registered user's last name

    ArrayList<String> usernames = new ArrayList<>();//array list to store users' usernames
    ArrayList<String> passwords = new ArrayList<>();//array list to store users' passwords
    ArrayList<String> badPasswords = new ArrayList<>();//array list to store bad passwords
    ArrayList<String> firstNames = new ArrayList<>();//array list to store users' first names
    ArrayList<String> lastNames = new ArrayList<>();//array list to store users' last names
    ArrayList<String> emailAddresses = new ArrayList<>();//array list to store users' email addresses

    File users = new File("user.txt");//create a file object for the users

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User Login System"));

        jLabel1.setText("Username:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("New User Account");

        jLabel4.setText("Enter Your User Name: ");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter Your Email Address: ");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Your Password: ");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter Your First Name: ");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Your Last Name: ");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Forgot Password?");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel12.setText("Enter First Name:");

        jLabel13.setText("Enter New Password: ");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jButton3.setText("Change Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(138, 138, 138))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel14))
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton2))
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        //USERNAME FIELD (for returning user)
        //check to see if the username is in the file

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        //PASSWORD FIELD (for returning user)
        //check to see if the password is in the file

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //LOGIN BUTTON (for returning user)
        oldUsername = jTextField1.getText();//get username
        oldPassword = jTextField2.getText();//get password

        clearFields();//clear the other status labels 

        String oldEncryptedPass = "";//string to store encrypted version of password

        //ENCRYPT THE ENTERED PASSWORD
        try {
            MessageDigest mesd = MessageDigest.getInstance("SHA-256");
            mesd.update(oldPassword.getBytes());
            byte byteData2[] = mesd.digest();

            for (int i = 0; i < byteData2.length; ++i) {
                oldEncryptedPass += (Integer.toHexString((byteData2[i] & 0xFF) | 0x100).substring(1, 3));
            }

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Check to see if username and encrypted password match a username and encrypted password which were stored in the user file
        if ((usernames.contains(oldUsername)) && (passwords.contains(oldEncryptedPass))) {//if both the username and the correct password are in the user file
            jLabel10.setText("Valid Login");

        } else {//if it does not match anything in the file
            jLabel10.setText("Not Registered");//tell the user that they are not registered
        }

        jTextField1.setText("");//clear the text field
        jTextField2.setText("");//clear the text field
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        //ENTER NEW USERNAME

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        //ENTER EMAIL ADDRESS

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        //ENTER NEW PASSWORD

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//REGISTER NEW USER        

        clearFields();//clear the other status labels 

//READ BAD PASSWORDS
        File badPasswordsFile = new File("badPasswords.txt");

        try {
            Scanner nextPass = new Scanner(badPasswordsFile).useDelimiter("\\s*:\\s*");
            while (nextPass.hasNext()) {
                String inPass = nextPass.next();
                badPasswords.add(inPass);//add the bad passwords from the bad passwords file to the badPasswords array list
            }

        } catch (FileNotFoundException ex) {
            System.out.printf("ERROR %s\n", ex);
        }

        newPassword = jTextField5.getText();//get the new user's password
        
        newEmailAddress = jTextField4.getText();//get the new user's email address
        boolean twoSymbol = false;//Variable to see if there ate two @ in the email address
        int n = newEmailAddress.length();
        int numAts = 0;//Counts the number of @ symbols in the email address
        for (int i = 1; i < n; i++)//Loops through the email address to find @ symbols
        {
            char c = newEmailAddress.charAt(i);   
            if (c == '@')//If email address has an @
            {
                numAts ++;//add 1 to the counter
            }
        }
        
        if (numAts > 1)//If the number of @'s in the email address is greater than 1
        {
            twoSymbol = true;//Set twoSymbol to true
        } else{//If it is below 1
            twoSymbol = false;//Set twoSymbol to false
        }
 
        if (badPasswords.contains(newPassword)||newPassword.length()<4) {//if the password that the user tries to register with is bad or less than 4 characters
            jLabel9.setText("Weak Password");//tell the user that the password is weak
            jTextField5.setText("");//delete the text in the password textfield to let them enter a new password
           
        }else if(newEmailAddress.indexOf("@")==-1||newEmailAddress.indexOf(".")==-1){//If the email does not have an @ symbol or a .
            jLabel9.setText("Invalid Email");//tell the user that the email is invalid
            jTextField4.setText("");//clear the email text field
        }else if(newEmailAddress.indexOf(".")!=newEmailAddress.length()-3&&newEmailAddress.indexOf(".")!=newEmailAddress.length()-4){//If the period in the email address is not at the third or fourth last position
            jLabel9.setText("Invalid Email");//tell the user that the email is invalid
            jTextField4.setText("");//clear the email text field
        }else if(newEmailAddress.indexOf("@")==0||newEmailAddress.indexOf(" ")!=-1){//If the @ symbol is the first character in the email or if a space is in the email 
            jLabel9.setText("Invalid Email");//tell the user that the email is invalid
            jTextField4.setText("");//clear the email text field
        }else if(twoSymbol == true){//if twoSYmbol is true
            jLabel9.setText("Invalid Email");//tell the user that the email is invalid
            jTextField4.setText("");//clear the email text field
        }else if ((jTextField5.getText().equals(""))||(jTextField6.getText().equals(""))||(jTextField4.getText().equals(""))||(jTextField7.getText().equals(""))||(jTextField3.getText().equals(""))){
            
            jLabel9.setText("Please Fill Out All Fields");
                                
        } else {//if the password and email is good

            jLabel9.setText("Successfully Registered");//display successful registration message to user

            //ENCRYPT THE USER'S PASSWORD
            MessageDigest mesd = null;
            try {
                mesd = MessageDigest.getInstance("SHA-256");
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(Level.SEVERE, null, ex);
            }

            mesd.update(newPassword.getBytes());
            byte byteData[] = mesd.digest();
            String encryptedPass = "";

            for (int i = 0; i < byteData.length; ++i) {
                encryptedPass += (Integer.toHexString((byteData[i] & 0xFF) | 0x100).substring(1, 3));
            }

            passwords.add(encryptedPass);//add the encrypted password to the array of passwords

            jTextField5.setText("");//clear the password text field

            newFirstName = jTextField6.getText();//get the new user's first name
            firstNames.add(newFirstName);//add the user's first name to the first names array
            jTextField6.setText("");//clear the username text field

            newLastName = jTextField7.getText();//get the new user's last name
            lastNames.add(newLastName);//add the user's last name to the last names array
            jTextField7.setText("");//clear the last name text field

            newUsername = jTextField3.getText();//get the new user's username
            usernames.add(newUsername);//add the user's username to the usernames array
            jTextField3.setText("");//clear the username text field

            
            emailAddresses.add(newEmailAddress);//add the user's email address to the email addresses array
            jTextField4.setText("");//clear the email text field

        }

        write();//write all user information to the user file

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        //NEW USER'S FIRST NAME

    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        //NEW USER'S LAST NAME

    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        //USER ENTERS THEIR FIRST NAME TO CHANGE THEIR PASSWORD

    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //CHANGE USER'S PASSWORD

        clearFields();//clear the other status labels 
        String changeUser = jTextField8.getText();//get the first name of the user who wants to change their password
        String changePassword = jTextField9.getText();//get the password that the user wants to change their password to 
        String changedEncryptedPass = "";//string to store the encrypted version of the new password

        //ENCRYPT THE PASSWORD
        try {
            MessageDigest mesd = MessageDigest.getInstance("SHA-256");
            mesd.update(changePassword.getBytes());
            byte byteData3[] = mesd.digest();

            for (int i = 0; i < byteData3.length; ++i) {
                changedEncryptedPass += (Integer.toHexString((byteData3[i] & 0xFF) | 0x100).substring(1, 3));
            }

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        int pos = 0;//variable to store position of user who wants to change passoword in the array lists

        if (firstNames.contains(changeUser)) {//if the user is a registered user

            pos = firstNames.indexOf(changeUser);//find the position of the user in the first names array list
            passwords.set(pos, changedEncryptedPass);//set the password in the same position in the passwords array list to the new encrypted password
            jLabel15.setText("Password Successfully Reset");//display successful password change message to user
            write();

        } else {

            jLabel15.setText("Not a Registered User.");//if the user is not a registered user, 
            jLabel16.setText("(Please make sure that you are entering your first name if you are already registered)");//reminder to user to enter first name
        }

        jTextField8.setText("");
        jTextField9.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        //USER ENTERS THEIR NEW PASSWORD

    }//GEN-LAST:event_jTextField9ActionPerformed

    public static void main(String args[]) {

         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SathishGauthamSecureLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SathishGauthamSecureLogin().setVisible(true);
            }
        });
    }

    /**
     * Writes the users to the users file
     */
    private void write() {
        //WRITE IN NEW USER
        try {
            try (PrintWriter outUsers = new PrintWriter(users)) {//writing object for first names                

                //print the arrays
                for (int c = 0; c < firstNames.size(); c++) {//keep writing to the user file as long as there are users

                    outUsers.print(firstNames.get(c));
                    outUsers.print(";");

                    outUsers.print(lastNames.get(c));
                    outUsers.print(";");

                    outUsers.print(usernames.get(c));
                    outUsers.print(";");

                    outUsers.print(emailAddresses.get(c));
                    outUsers.print(";");

                    outUsers.print(passwords.get(c));
                    outUsers.println(";");
                                     
                }
                
                outUsers.close();
            }
        } catch (IOException ex) {
            System.out.printf("ERROR: %s\n", ex);
        }
    }

    /**
     * Reads the user information in the users file to the array lists
     */
    private void read() {
        //READ IN OLD USERS
        if (users.length() != 0) {//if a user is already stored in the users file, read in the old users into the array
            try {
                Scanner input = new Scanner(users).useDelimiter("\\s*;\\s*");

                while (input.hasNext()) {//while there are still more users in the file that have not been read
                    String inName = input.next();
                    firstNames.add(inName);//add the next first name to the firstNames array list

                    String inLastName = input.next();
                    lastNames.add(inLastName);//add the next last name to the lastNames array list

                    String inUsername = input.next();
                    usernames.add(inUsername);//add the next username to the usernames array list

                    String inEmail = input.next();
                    emailAddresses.add(inEmail);//add the next email address to the email addresses array list

                    String inPassword = input.next();
                    passwords.add(inPassword);//add the next password to the passwords array list
                }

            } catch (FileNotFoundException ex) {
                System.out.printf("ERROR %s\n", ex);
            }
        }
    }
   

    /**
     * Clear the text fields from previous user actions around the login system
     * screen to only display the results of the action that the user just did
     */
    private void clearFields() {
        jLabel10.setText("");//clear user login label
        jLabel9.setText("");//clear registration label
        jLabel15.setText("");//clear change password label
        jLabel16.setText("");//clear the reminder to enter first name
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
